name: Check Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

defaults:
  run:
    shell: bash -l {0}

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: voici-dev
          create-args: >-
            python=3.9
            yarn=3
            pip
            jupyter_releaser

    - id: prep-release
      run: |
        export RH_DRY_RUN="true"
        export GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export RH_VERSION_SPEC=${{ next }}
        python -m jupyter_releaser.actions.prep_release

    - id: populate-release
      run: |
        export RH_DRY_RUN="true"
        export GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export RH_RELEASE_URL=${{ steps.prep-release.outputs.release_url }}
        export YARN_UNSAFE_HTTP_WHITELIST=0.0.0.0
        python -m jupyter_releaser.actions.populate_release

    - id: finalize-release
      run: |
        export RH_DRY_RUN="true"
        export GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export RH_RELEASE_URL=${{ steps.populate-release.outputs.release_url }}
        python -m jupyter_releaser.actions.finalize_release

      - name: Upload Distributions
        uses: actions/upload-artifact@v3
        with:
          name: jupytercad-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
