name: Check Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup yarn
        run: npm install -g yarn@3

      - name: Check Release
        uses: jupyter-server/jupyter_releaser/.github/actions/check-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version_spec: next

      - name: Upload Distributions
        uses: actions/upload-artifact@v3
        with:
          name: voici-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
