name: Build And Check Frontend Packages

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: "0 2 * * 1-5"  # run on weekdays at 2:00am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        extra-specs: |
          python=${{ matrix.python_version }}

    - name: Lint
      run: |
        yarn
        yarn run eslint:check
        yarn run prettier:check
