name: Build And Check Frontend Packages

defaults:
  run:
    shell: bash -l {0}

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: "0 2 * * 1-5"  # run on weekdays at 2:00am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml

    - name: Lint
      run: |
        jlpm
        jlpm run eslint:check
        jlpm run prettier:check
      working-directory:
        python/voici-core
