name: Update UI-tests References

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash -l {0}

jobs:
  update-reference-screenshots:
    name: Update UI Tests References
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'update playwright snapshots') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git to use https
        run: git config --global hub.protocol https

      - name: Checkout the branch from the PR that triggered the job
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Micromamba
        uses: mamba-org/provision-with-micromamba@main

      - name: Install dependencies
        run: |
          python -m pip install .
          cd ui-tests
          yarn install --frozen-lockfile

      - uses: jupyterlab/maintainer-tools/.github/actions/update-snapshots@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          server_url: http-get://localhost:8866/
          test_folder: ui-tests
